const SAVE_TRACK_LOG = 'SAVE_TRACK_LOG';
const GET_PROJECTS = 'GET_PROJECTS';
const GET_TASKS = 'GET_TASKS';
const GET_TRACK_LOG = 'GET_TRACK_LOG';
const EDIT_TRACK_LOG = 'EDIT_TRACK_LOG';
const DELETE_TRACK_LOG = 'DELETE_TRACK_LOG';
const UPDATE_TRACK_LOG = 'UPDATE_TRACK_LOG';
const ADD_CLIENT = 'SAVE_CLIENT';
const GET_CLIENT = 'GET_CLIENT';
const EDIT_CLIENT = 'EDIT_CLIENT';
const UPDATE_CLIENT = 'UPDATE_CLIENT';
const DELETE_CLIENT = 'DELETE_CLIENT';


export {
    SAVE_TRACK_LOG,
    GET_PROJECTS,
    GET_TASKS,
    GET_TRACK_LOG,
    EDIT_TRACK_LOG,
    DELETE_TRACK_LOG,
    UPDATE_TRACK_LOG,
    ADD_CLIENT,
    GET_CLIENT,
    EDIT_CLIENT,
    UPDATE_CLIENT,
    DELETE_CLIENT
}