const SAVE_TRACK_LOG = 'SAVE_TRACK_LOG';
const GET_PROJECTS = 'GET_PROJECTS';
const GET_TASKS = 'GET_TASKS';
const GET_TRACK_LOG = 'GET_TRACK_LOG';
const EDIT_TRACK_LOG = 'EDIT_TRACK_LOG';
const DELETE_TRACK_LOG = 'DELETE_TRACK_LOG';
const UPDATE_TRACK_LOG = 'UPDATE_TRACK_LOG';

export {
    SAVE_TRACK_LOG,
    GET_PROJECTS,
    GET_TASKS,
    GET_TRACK_LOG,
    EDIT_TRACK_LOG,
    DELETE_TRACK_LOG,
    UPDATE_TRACK_LOG
}